<?php
$config_db ['dev'] =  array(
  'database' => 'tuk32945_unidrupal_dev',
  'username' => 'tuk32945',
  'password' => 'muorFhb3qY6',
  'prefix' => '',
  'host' => 'drupal-dev-db1.temple.edu',
  'port' => '',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
); //dev settings

$config_db ['test'] = array(
 'database' => 'tuk32945_unidrupal_test',
 'username' => 'tuk32945',
 'password' => 'muorFhb3qY6',
 'prefix' => '',
 'host' => 'drupal-dev-db1.temple.edu',
 'port' => '',
 'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
 'driver' => 'mysql',
 ); // test settings

$config_db ['www'] = array(
    'database' => 'tuk32945_unidrupal_www',
    'username' => 'tuk32945',
    'password' => 'muorFhb3qY6',
    'prefix' => '',
    'host' => 'drupal-dev-db1.temple.edu',
    'port' => '',
    'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
    'driver' => 'mysql',
  ); // prod settings
