<?php


$config_splits = array(
  'config_split.config_split.dev_disable_admin_uis' => array(
      'folder' => dirname(DRUPAL_ROOT) . '/drupal_config/split/origin/dev_disable_admin_uis'
  ),
  'config_split.config_split.prod__syslog_tweak' => array(
      'folder' => dirname(DRUPAL_ROOT) . '/drupal_config/split/origin/prod_syslog_tweak'
  ),
  'config_split.config_split.prod_enable_tu_modules' => array(
      'folder' => dirname(DRUPAL_ROOT) . '/drupal_config/split/origin/prod_enable_tu_modules'
  ),
  'config_split.config_split.tu_split_black_prod_ui_disable' => array(
      'folder' => dirname(DRUPAL_ROOT) . '/drupal_config/split/tu_split_black_prod_ui_disable'
  ),
);
